Repository adaptlearning/adapt-contrib-hotgraphic, pull requests merged in 2022-04, with the labels that each got.

#219 issue/3156 Normalised notify classes and attributes with tutor
  js/hotgraphicView.js
Labels: bug

#218 issue/2799 Removed redundant behaviour
  README.md
  bower.json
  js/adapt-contrib-hotgraphic.js
  js/hotgraphicPopupView.js
  js/hotgraphicView.js
Labels: breaking

#225 add "_isMobileTextBelowImage"
  README.md
  properties.schema
Labels: enhancement
