Repository adaptlearning/adapt-contrib-hotgraphic, pull requests merged in 2022-07, with the labels that each got.

#230 Converted button divs to spans
  less/hotgraphic.less
  templates/hotgraphic.hbs
  templates/hotgraphicPopup.hbs
Labels: bug

#234 New: Issue and pr project addition automation (Fixes #3315)
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/workflows/addtomainproject.yml
Labels: enhancement

#231 #226 Resolves add completion statuses to pins/icons
  less/hotgraphic.less
  templates/hotgraphic.hbs
Labels: enhancement

#233 #232 Resolves Add completion statuses when using tile layout
  less/hotgraphic.less
  templates/hotgraphic.hbs
Labels: bug, accessibility

#237 Fix: Added gitignore for release automation
  .gitignore
Labels: enhancement
