Repository adaptlearning/adapt-contrib-hotgraphic, pull requests merged in 2023-05, with the labels that each got.

#240 New: support for tooltips (refs #239)
  README.md
  example.json
  js/hotgraphicModel.js
  properties.schema
  schema/component.schema.json
  templates/hotgraphicLayoutPins.jsx
Labels: enhancement

#266 Fix: Item popup title missing ARIA heading role (fixes #265)
  templates/hotgraphicPopup.jsx
Labels: bug, accessibility

#272 Fix: mobileInstruction inputType changed from TextArea to Text (fixes #271)
  properties.schema
  schema/component.schema.json
Labels: bug

#274 Fix: compile reactHelpers (fixes #273)
  templates/hotgraphicPopup.jsx
Labels: bug, accessibility
